# Generated by Django 2.2 on 2019-12-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191221_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_image',
            new_name='header_image',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='haha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
